name: Sparta Nest.js CD

on:
  workflow_dispatch: # 수동 실행
  workflow_run: # 특정 workflow가 실행됐을 때
    workflows: ['Sparta Nest.js CI'] # CI workflow
    types: [completed] # 완료 되었을 때
    branches: [main] # main 브랜치

jobs:
  deploy:
    # workflow 완료 후 결과가 성공 일 때
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # 작업을 실행 할 VM의 OS 지정
    runs-on: ubuntu-24.04
    timeout-minutes: 3

    # 작업 내의 단위 작업(step)을 정의
    steps:
      # SSH 접속 후 명령을 통해서 배포 진행
      - name: Configure SSH
        run: |

          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ec2.key
          chmod 400 ~/.ssh/ec2.key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ec2.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_EC2_PEM_KEY }}
          SSH_HOST: ${{ secrets.AWS_EC2_HOST }}

      - name: Deploy to EC2
        run: ssh ec2 'cd /home/ubuntu/Give_me_the_ticket && git switch main && git pull && echo "${{ secrets.ENV }}" > .env && ./scripts/run.sh'